//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace BFP.WinService.Data {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Configuration;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSMSSoap", Namespace="http://tempuri.org/")]
    public partial class ServiceSMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EnviaSMSOperationCompleted;
        
        /// <remarks/>
        public ServiceSMS() {
            this.Url = ConfigurationManager.ConnectionStrings["proxySMS_YP"].ToString().Trim();
        }
        
        /// <remarks/>
        public event EnviaSMSCompletedEventHandler EnviaSMSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviaSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviaSMS(string serial, string pin, string mobile, string message, string codigoCorto) {
            object[] results = this.Invoke("EnviaSMS", new object[] {
                        serial,
                        pin,
                        mobile,
                        message,
                        codigoCorto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEnviaSMS(string serial, string pin, string mobile, string message, string codigoCorto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EnviaSMS", new object[] {
                        serial,
                        pin,
                        mobile,
                        message,
                        codigoCorto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndEnviaSMS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviaSMSAsync(string serial, string pin, string mobile, string message, string codigoCorto) {
            this.EnviaSMSAsync(serial, pin, mobile, message, codigoCorto, null);
        }
        
        /// <remarks/>
        public void EnviaSMSAsync(string serial, string pin, string mobile, string message, string codigoCorto, object userState) {
            if ((this.EnviaSMSOperationCompleted == null)) {
                this.EnviaSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaSMSOperationCompleted);
            }
            this.InvokeAsync("EnviaSMS", new object[] {
                        serial,
                        pin,
                        mobile,
                        message,
                        codigoCorto}, this.EnviaSMSOperationCompleted, userState);
        }
        
        private void OnEnviaSMSOperationCompleted(object arg) {
            if ((this.EnviaSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaSMSCompleted(this, new EnviaSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void EnviaSMSCompletedEventHandler(object sender, EnviaSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviaSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
