//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.BFP.ServiceBC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BFP.ServiceBC.ServiceBancaCelular")]
    public interface ServiceBancaCelular {
        
        // CODEGEN: Generating message contract since message OperacionBancaCelularRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OperacionBancaCelular", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Test.BFP.ServiceBC.OperacionBancaCelularResponse OperacionBancaCelular(Test.BFP.ServiceBC.OperacionBancaCelularRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioCredencial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EResultadoMensajeMT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codRetField;
        
        private string mensajeMTField;
        
        private string fechaField;
        
        private string horaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CodRet {
            get {
                return this.codRetField;
            }
            set {
                this.codRetField = value;
                this.RaisePropertyChanged("CodRet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MensajeMT {
            get {
                return this.mensajeMTField;
            }
            set {
                this.mensajeMTField = value;
                this.RaisePropertyChanged("MensajeMT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
                this.RaisePropertyChanged("Hora");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OperacionBancaCelular", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OperacionBancaCelularRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Test.BFP.ServiceBC.UsuarioCredencial UsuarioCredencial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strIdTransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intIdOperacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strNumeroTelefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int intIdOperadora;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strIdTransaccionVerifica;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string strParametrosOperacion;
        
        public OperacionBancaCelularRequest() {
        }
        
        public OperacionBancaCelularRequest(Test.BFP.ServiceBC.UsuarioCredencial UsuarioCredencial, string strIdTransaccion, int intIdOperacion, string strNumeroTelefono, int intIdOperadora, string strIdTransaccionVerifica, string strParametrosOperacion) {
            this.UsuarioCredencial = UsuarioCredencial;
            this.strIdTransaccion = strIdTransaccion;
            this.intIdOperacion = intIdOperacion;
            this.strNumeroTelefono = strNumeroTelefono;
            this.intIdOperadora = intIdOperadora;
            this.strIdTransaccionVerifica = strIdTransaccionVerifica;
            this.strParametrosOperacion = strParametrosOperacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OperacionBancaCelularResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OperacionBancaCelularResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Test.BFP.ServiceBC.EResultadoMensajeMT OperacionBancaCelularResult;
        
        public OperacionBancaCelularResponse() {
        }
        
        public OperacionBancaCelularResponse(Test.BFP.ServiceBC.EResultadoMensajeMT OperacionBancaCelularResult) {
            this.OperacionBancaCelularResult = OperacionBancaCelularResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceBancaCelularChannel : Test.BFP.ServiceBC.ServiceBancaCelular, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceBancaCelularClient : System.ServiceModel.ClientBase<Test.BFP.ServiceBC.ServiceBancaCelular>, Test.BFP.ServiceBC.ServiceBancaCelular {
        
        public ServiceBancaCelularClient() {
        }
        
        public ServiceBancaCelularClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBancaCelularClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBancaCelularClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBancaCelularClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.BFP.ServiceBC.OperacionBancaCelularResponse Test.BFP.ServiceBC.ServiceBancaCelular.OperacionBancaCelular(Test.BFP.ServiceBC.OperacionBancaCelularRequest request) {
            return base.Channel.OperacionBancaCelular(request);
        }
        
        public Test.BFP.ServiceBC.EResultadoMensajeMT OperacionBancaCelular(Test.BFP.ServiceBC.UsuarioCredencial UsuarioCredencial, string strIdTransaccion, int intIdOperacion, string strNumeroTelefono, int intIdOperadora, string strIdTransaccionVerifica, string strParametrosOperacion) {
            Test.BFP.ServiceBC.OperacionBancaCelularRequest inValue = new Test.BFP.ServiceBC.OperacionBancaCelularRequest();
            inValue.UsuarioCredencial = UsuarioCredencial;
            inValue.strIdTransaccion = strIdTransaccion;
            inValue.intIdOperacion = intIdOperacion;
            inValue.strNumeroTelefono = strNumeroTelefono;
            inValue.intIdOperadora = intIdOperadora;
            inValue.strIdTransaccionVerifica = strIdTransaccionVerifica;
            inValue.strParametrosOperacion = strParametrosOperacion;
            Test.BFP.ServiceBC.OperacionBancaCelularResponse retVal = ((Test.BFP.ServiceBC.ServiceBancaCelular)(this)).OperacionBancaCelular(inValue);
            return retVal.OperacionBancaCelularResult;
        }
    }
}
