//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace BFP.BancaCelular.Data {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Configuration;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EncriptadorSoapBinding", Namespace="http://service.encriptador.financiero.com.pe")]
    public partial class EncriptadorService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback encriptaOperationCompleted;
        
        private System.Threading.SendOrPostCallback desencriptaOperationCompleted;
        
        /// <remarks/>
        public EncriptadorService() {
            this.Url = ConfigurationManager.ConnectionStrings["proxyEncriptador"].ToString().Trim();
        }
        
        /// <remarks/>
        public event encriptaCompletedEventHandler encriptaCompleted;
        
        /// <remarks/>
        public event desencriptaCompletedEventHandler desencriptaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.encriptador.financiero.com.pe", ResponseNamespace="http://service.encriptador.financiero.com.pe", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("encriptaReturn")]
        public string encripta(string cadena) {
            object[] results = this.Invoke("encripta", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginencripta(string cadena, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("encripta", new object[] {
                        cadena}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endencripta(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void encriptaAsync(string cadena) {
            this.encriptaAsync(cadena, null);
        }
        
        /// <remarks/>
        public void encriptaAsync(string cadena, object userState) {
            if ((this.encriptaOperationCompleted == null)) {
                this.encriptaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnencriptaOperationCompleted);
            }
            this.InvokeAsync("encripta", new object[] {
                        cadena}, this.encriptaOperationCompleted, userState);
        }
        
        private void OnencriptaOperationCompleted(object arg) {
            if ((this.encriptaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.encriptaCompleted(this, new encriptaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.encriptador.financiero.com.pe", ResponseNamespace="http://service.encriptador.financiero.com.pe", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("desencriptaReturn")]
        public string desencripta(string cadena) {
            object[] results = this.Invoke("desencripta", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindesencripta(string cadena, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("desencripta", new object[] {
                        cadena}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Enddesencripta(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void desencriptaAsync(string cadena) {
            this.desencriptaAsync(cadena, null);
        }
        
        /// <remarks/>
        public void desencriptaAsync(string cadena, object userState) {
            if ((this.desencriptaOperationCompleted == null)) {
                this.desencriptaOperationCompleted = new System.Threading.SendOrPostCallback(this.OndesencriptaOperationCompleted);
            }
            this.InvokeAsync("desencripta", new object[] {
                        cadena}, this.desencriptaOperationCompleted, userState);
        }
        
        private void OndesencriptaOperationCompleted(object arg) {
            if ((this.desencriptaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.desencriptaCompleted(this, new desencriptaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void encriptaCompletedEventHandler(object sender, encriptaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class encriptaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal encriptaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void desencriptaCompletedEventHandler(object sender, desencriptaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class desencriptaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal desencriptaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
