//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace BFP.WebServiceYP {
    using System.Diagnostics;
    using System.EnterpriseServices;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Configuration;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public partial class metroLine : System.Web.Services.Protocols.HttpGetClientProtocol {
        
        private System.Threading.SendOrPostCallback sendShortMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendPremiumMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendConfirmMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendFreeMessageOperationCompleted;
        
        /// <remarks/>
        public metroLine() {
            this.Url = ConfigurationManager.ConnectionStrings["proxyYP"].ToString().Trim();
        }
        
        /// <remarks/>
        public event sendShortMessageCompletedEventHandler sendShortMessageCompleted;
        
        /// <remarks/>
        public event sendPremiumMessageCompletedEventHandler sendPremiumMessageCompleted;
        
        /// <remarks/>
        public event sendConfirmMessageCompletedEventHandler sendConfirmMessageCompleted;
        
        /// <remarks/>
        public event sendFreeMessageCompletedEventHandler sendFreeMessageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.HttpMethodAttribute(typeof(System.Web.Services.Protocols.XmlReturnReader), typeof(System.Web.Services.Protocols.UrlParameterWriter))]
        [return: System.Xml.Serialization.XmlRootAttribute("string", Namespace="http://yellowpepper.com/webservices/literalTypes", IsNullable=true)]
        public string sendShortMessage(string Serial, string Pin, string Mobile, string Message, string Sender) {
            return ((string)(this.Invoke("sendShortMessage", (this.Url + "/sendShortMessage"), new object[] {
                        Serial,
                        Pin,
                        Mobile,
                        Message,
                        Sender})));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsendShortMessage(string Serial, string Pin, string Mobile, string Message, string Sender, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sendShortMessage", (this.Url + "/sendShortMessage"), new object[] {
                        Serial,
                        Pin,
                        Mobile,
                        Message,
                        Sender}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsendShortMessage(System.IAsyncResult asyncResult) {
            return ((string)(this.EndInvoke(asyncResult)));
        }
        
        /// <remarks/>
        public void sendShortMessageAsync(string Serial, string Pin, string Mobile, string Message, string Sender) {
            this.sendShortMessageAsync(Serial, Pin, Mobile, Message, Sender, null);
        }
        
        /// <remarks/>
        public void sendShortMessageAsync(string Serial, string Pin, string Mobile, string Message, string Sender, object userState) {
            if ((this.sendShortMessageOperationCompleted == null)) {
                this.sendShortMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendShortMessageOperationCompleted);
            }
            this.InvokeAsync("sendShortMessage", (this.Url + "/sendShortMessage"), new object[] {
                        Serial,
                        Pin,
                        Mobile,
                        Message,
                        Sender}, this.sendShortMessageOperationCompleted, userState);
        }
        
        private void OnsendShortMessageOperationCompleted(object arg) {
            if ((this.sendShortMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendShortMessageCompleted(this, new sendShortMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.HttpMethodAttribute(typeof(System.Web.Services.Protocols.XmlReturnReader), typeof(System.Web.Services.Protocols.UrlParameterWriter))]
        [return: System.Xml.Serialization.XmlRootAttribute("string", Namespace="http://yellowpepper.com/webservices/literalTypes", IsNullable=true)]
        public string sendPremiumMessage(string Serial, string Pin, string Mobile, string Message, string Sender) {
            return ((string)(this.Invoke("sendPremiumMessage", (this.Url + "/sendPremiumMessage"), new object[] {
                        Serial,
                        Pin,
                        Mobile,
                        Message,
                        Sender})));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsendPremiumMessage(string Serial, string Pin, string Mobile, string Message, string Sender, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sendPremiumMessage", (this.Url + "/sendPremiumMessage"), new object[] {
                        Serial,
                        Pin,
                        Mobile,
                        Message,
                        Sender}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsendPremiumMessage(System.IAsyncResult asyncResult) {
            return ((string)(this.EndInvoke(asyncResult)));
        }
        
        /// <remarks/>
        public void sendPremiumMessageAsync(string Serial, string Pin, string Mobile, string Message, string Sender) {
            this.sendPremiumMessageAsync(Serial, Pin, Mobile, Message, Sender, null);
        }
        
        /// <remarks/>
        public void sendPremiumMessageAsync(string Serial, string Pin, string Mobile, string Message, string Sender, object userState) {
            if ((this.sendPremiumMessageOperationCompleted == null)) {
                this.sendPremiumMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendPremiumMessageOperationCompleted);
            }
            this.InvokeAsync("sendPremiumMessage", (this.Url + "/sendPremiumMessage"), new object[] {
                        Serial,
                        Pin,
                        Mobile,
                        Message,
                        Sender}, this.sendPremiumMessageOperationCompleted, userState);
        }
        
        private void OnsendPremiumMessageOperationCompleted(object arg) {
            if ((this.sendPremiumMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendPremiumMessageCompleted(this, new sendPremiumMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.HttpMethodAttribute(typeof(System.Web.Services.Protocols.XmlReturnReader), typeof(System.Web.Services.Protocols.UrlParameterWriter))]
        [return: System.Xml.Serialization.XmlRootAttribute("string", Namespace="http://yellowpepper.com/webservices/literalTypes", IsNullable=true)]
        public string sendConfirmMessage(string Serial, string Pin, string Mobile, string Message, string Sender) {
            return ((string)(this.Invoke("sendConfirmMessage", (this.Url + "/sendConfirmMessage"), new object[] {
                        Serial,
                        Pin,
                        Mobile,
                        Message,
                        Sender})));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsendConfirmMessage(string Serial, string Pin, string Mobile, string Message, string Sender, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sendConfirmMessage", (this.Url + "/sendConfirmMessage"), new object[] {
                        Serial,
                        Pin,
                        Mobile,
                        Message,
                        Sender}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsendConfirmMessage(System.IAsyncResult asyncResult) {
            return ((string)(this.EndInvoke(asyncResult)));
        }
        
        /// <remarks/>
        public void sendConfirmMessageAsync(string Serial, string Pin, string Mobile, string Message, string Sender) {
            this.sendConfirmMessageAsync(Serial, Pin, Mobile, Message, Sender, null);
        }
        
        /// <remarks/>
        public void sendConfirmMessageAsync(string Serial, string Pin, string Mobile, string Message, string Sender, object userState) {
            if ((this.sendConfirmMessageOperationCompleted == null)) {
                this.sendConfirmMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendConfirmMessageOperationCompleted);
            }
            this.InvokeAsync("sendConfirmMessage", (this.Url + "/sendConfirmMessage"), new object[] {
                        Serial,
                        Pin,
                        Mobile,
                        Message,
                        Sender}, this.sendConfirmMessageOperationCompleted, userState);
        }
        
        private void OnsendConfirmMessageOperationCompleted(object arg) {
            if ((this.sendConfirmMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendConfirmMessageCompleted(this, new sendConfirmMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.HttpMethodAttribute(typeof(System.Web.Services.Protocols.XmlReturnReader), typeof(System.Web.Services.Protocols.UrlParameterWriter))]
        [return: System.Xml.Serialization.XmlRootAttribute("string", Namespace="http://yellowpepper.com/webservices/literalTypes", IsNullable=true)]
        public string sendFreeMessage(string Serial, string Pin, string Mobile, string Message, string Sender) {
            return ((string)(this.Invoke("sendFreeMessage", (this.Url + "/sendFreeMessage"), new object[] {
                        Serial,
                        Pin,
                        Mobile,
                        Message,
                        Sender})));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsendFreeMessage(string Serial, string Pin, string Mobile, string Message, string Sender, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sendFreeMessage", (this.Url + "/sendFreeMessage"), new object[] {
                        Serial,
                        Pin,
                        Mobile,
                        Message,
                        Sender}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsendFreeMessage(System.IAsyncResult asyncResult) {
            return ((string)(this.EndInvoke(asyncResult)));
        }
        
        /// <remarks/>
        public void sendFreeMessageAsync(string Serial, string Pin, string Mobile, string Message, string Sender) {
            this.sendFreeMessageAsync(Serial, Pin, Mobile, Message, Sender, null);
        }
        
        /// <remarks/>
        public void sendFreeMessageAsync(string Serial, string Pin, string Mobile, string Message, string Sender, object userState) {
            if ((this.sendFreeMessageOperationCompleted == null)) {
                this.sendFreeMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendFreeMessageOperationCompleted);
            }
            this.InvokeAsync("sendFreeMessage", (this.Url + "/sendFreeMessage"), new object[] {
                        Serial,
                        Pin,
                        Mobile,
                        Message,
                        Sender}, this.sendFreeMessageOperationCompleted, userState);
        }
        
        private void OnsendFreeMessageOperationCompleted(object arg) {
            if ((this.sendFreeMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendFreeMessageCompleted(this, new sendFreeMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void sendShortMessageCompletedEventHandler(object sender, sendShortMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendShortMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendShortMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void sendPremiumMessageCompletedEventHandler(object sender, sendPremiumMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendPremiumMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendPremiumMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void sendConfirmMessageCompletedEventHandler(object sender, sendConfirmMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendConfirmMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendConfirmMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void sendFreeMessageCompletedEventHandler(object sender, sendFreeMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendFreeMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendFreeMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
